---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: grafana
spec:
  storageClassName: "gp3"
  existingClaim: grafana-pvc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
