service:
  type: ClusterIP
  metadata:
    name: grafana-service
adminUser: admin
adminPassword: secret

replicas: 1

persistence:
  type: pvc
  enabled: true
  storageClassName: "gp3"
  accessModes:
    - ReadWriteOnce
  size: 15Gi
  # annotations: {}
  existingClaim: grafana-pvc


