apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp3"
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-07d3e73d411fc7dc5
    fsType: ext4
