apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-deployment-demo
  labels:
    app: emailservice-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emailservice-demo
  template:
    metadata:
      labels:
        app: emailservice-demo
    spec:
      containers:
        - name: react-site-kuber-container
          image: alexeymihaylovdev/demo:1.1
          ports:
            - containerPort: 80
