version: "3.9"

services:
  mongo1:
    image: mongo:5
    container_name: mongo1
    volumes:
    - ./mongodb-entrypoint.sh:/mongodb-entrypoint.sh
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
    entrypoint: [ "/mongodb-entrypoint.sh"]
    ports:
      - "27017:27017"
    restart: always
    networks:
      - mongoCluster

  mongo2:
    image: mongo:5
    container_name: mongo2
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
    ports:
      - "27018:27017"
    restart: always
    networks:
      - mongoCluster
  mongo3:
    image: mongo:5
    container_name: mongo3
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
    ports:
      - "27019:27017"
    restart: always
    networks:
      - mongoCluster
  yolo5:
    image: yolo5
    container_name: yolo5
    ports:
        - "8081:8081"
    environment:
        - BUCKET_NAME=basharziv
    volumes:
      - C:\Users\bshar\.aws\credentials:/root/.aws/credentials
    networks:
      - mongoCluster
    restart: always

  poly:
    image: polybot
    container_name: poly
    ports:
        - "8443:8443"
    environment:
        - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
        - TELEGRAM_APP_URL=${TELEGRAM_APP_URL}
    volumes:
        - C:\Users\bshar\.aws\credentials:/root/.aws/credentials
        - ./polybot/bot.py:/app/bot.py
        - ./polybot/app.py:/app/app.py
    networks:
      - mongoCluster
    restart: always




networks:
  mongoCluster:
    driver: bridge