version: '3.9'
services:
#     https://www.mongodb.com/compatibility/docker
#docker run -d  -p 27017:27017 --name mongo1 --network mongoCluster mongo:5 
#docker run -d  -p 27018:27017 --name mongo2 --network mongoCluster mongo:5  
#docker run -d  -p 27019:27017 --name mongo3 --network mongoCluster mongo:5  
  mongo1:
    image: mongo:5
    container_name: mongo1
    ports:
      - "27017:27017"
    networks:
      - mongoCluster
    #docker run -v db-data:/data/db
    volumes:
      - db-data-m1:/data/db #Named volumes
  mongo2:
    image: mongo:5
    container_name: mongo2
    ports:
      - "27018:27017"
    networks:
      - mongoCluster
    #docker run -v db-data:/data/db
    volumes:
      - db-data-m2:/data/db #Named volumes
  mongo3:
    image: mongo:5
    container_name: mongo3
    ports:
      - "27019:27017"
    networks:
      - mongoCluster
    #docker run -v db-data:/data/db
    volumes:
      - db-data-m3:/data/db #Named volumes
  yolo5:
    image: mjoulani/yolo5:latest
    container_name: yolo5
    ports:
      - "8081:8081"
    volumes:
      - //c/Users/HP/.aws/credentials:/root/.aws/credentials 
      #- //c/Users/HP/.aws/credentials:/usr/src/app/.aws/credentials
      #- "%USERPROFILE%\\.aws\\credentials:/root/.aws/"
       #- "C:\\Users\\HP\\.aws\\credentials:/root/.aws/"

    environment:
      BUCKET_NAME: mjoulani-bucket
      #BUCKET_NAME: mjoulani-yolo
    networks:
      - mongoCluster
  polybot:
     #image: mjoulani/mybot:local1.1
     image: muh1
     container_name: mybot_c11
     ports:
      - "8443:8443"
     volumes:
      - //c/Users/HP/.aws/credentials:/root/.aws/credentials

     environment:
      # docker stack deploy 
      #- TELEGRAM_TOKEN=6671531875:AAG0nnI0XX_kneDgsOXNfclJi0V0tpuGwBU
      
      #- TELEGRAM_APP_URL=https://5711-93-173-73-255.ngrok-free.app
       TELEGRAM_TOKEN: /run/secrets/telegram_token
      #- TELEGRAM_TOKEN=6671531875:AAG0nnI0XX_kneDgsOXNfclJi0V0tpuGwBU
       TELEGRAM_APP_URL: https://5711-93-173-73-255.ngrok-free.app
     #command: sh -c 'echo "TELEGRAM_TOKEN=$TELEGRAM_TOKEN" && echo "TELEGRAM_APP_URL=$TELEGRAM_APP_URL" && python /usr/src/app/app.py' 


     networks:
      - mongoCluster
     secrets:
       - telegram_token

networks:
  mongoCluster:
    driver: bridge

secrets:
  #TELEGRAM_TOKEN:
  telegram_token:
    file: telegram_token.txt
    #file: TELEGRAM_TOKEN.txt
# container can share data between others mongo1,mongo2,mongo3
   
volumes:
   db-data-m1:
   db-data-m2:
   db-data-m3:
