#for testing propose
version: '3.9'
services:
  yolo5:
    image: mjoulani/yolo5.0
    container_name: yolo5_aws
    ports:
      - "8081:8081"
    volumes:
      - //c/Users/HP/.aws/credentials:/root/.aws/credentials 
 
      #- //c/Users/HP/.aws/credentials:/usr/src/app/.aws/credentials
      #- "%USERPROFILE%\\.aws\\credentials:/root/.aws/"
       #- "C:\\Users\\HP\\.aws\\credentials:/root/.aws/"