replicaCount: 1

releaseName: react-site

image:
  polyRepository: oferbakria/polybot
  polyTag: "latest"
  yoloRepository: oferbakria/yolo5
  yoloTag: "latest"

polyPort: 8443
yoloPort: 8441


service:
  port: 80

ingress:
  name: ingress-hosts
  host: oferbakria.atech-bot.click
  path: "/"
  tls: tls-secret-oferbakria

imagePullSecrets: dockerhub

maxSurge: 3

