replicaCount: 1

releaseName: react-site

image:
  polyRepository: oferbakria/poly
  polyTag: "1.3"
  yoloRepository: oferbakria/yolo
  yoloTag: "1.3"

polyPort: 8443
yoloPort: 8441


service:
  port: 80

ingress:
  name: ingress-hosts
  host: oferbakria.atech-bot.click
  path: "/"
  tls: tls-secret-oferbakria

imagePullSecrets: dockerhub

maxSurge: 3

