apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: mjoulani
  labels:
    k8s-app: node-exporter
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
  template:
    metadata:
      labels:
        k8s-app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:latest
        ports:
        - containerPort: 9100
          hostPort: 9100
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: mjoulani
  labels:
    k8s-app: node-exporter
spec:
  selector:
    k8s-app: node-exporter
  ports:
  - protocol: TCP
    port: 9100
    targetPort: 9100
