name: Trigger Jenkins on Push

on:
  push:
    branches:
    - muhamed_joulani_final_project

jobs:
  validate_and_trigger_jenkins_job:
    if: "!contains(github.event.head_commit.message, '[Jenkins]')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint Python Code
      run: |
        source venv/bin/activate
        pip install flake8
        # Specify your Python code directories here
        flake8 final_project/playbot/app.py final_project/playbot/bot.py final_project/yolo5/app.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    #     pip install pytest
    #     pytest

    - name: Install Java (required for Jenkins CLI)
      # - name: Run Unit Tests
      #     source venv/bin/activate
      #   run: |
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre

    - name: Download Jenkins CLI JAR
      run: |
        curl -O http://100.27.108.130:8080/jnlpJars/jenkins-cli.jar

    - name: Trigger Jenkins job using Jenkins CLI
      env:
        JENKINS_URL: http://100.27.108.130:8080
        JENKINS_USER: mjoulani
        JENKINS_PASSWORD: 1234
        #JENKINS_PASSWORD: ${{ secrets.JENKINS_PASSWORD }}  # Make sure to store Jenkins password securely in GitHub Secrets
        JOB_NAME: kube_jen
      run: |
        java -jar jenkins-cli.jar -s "$JENKINS_URL" -auth "$JENKINS_USER:$JENKINS_PASSWORD" build "$JOB_NAME"

