name: Trigger Jenkins on Push

on:
  push:
    branches:
      - muhamed_joulani_final_project

jobs:
  trigger_jenkins_job:
    runs-on: ubuntu-latest

    steps:
      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Trigger Jenkins job
        run: |
          JENKINS_URL="http://100.27.108.130:8080"
          JENKINS_USER="mjoulani"
          JENKINS_PASSWORD="1234"
          JOB_NAME="kub_jen"

          # Function to fetch Jenkins crumb with retry logic
          fetch_crumb() {
            local CRUMB_RESPONSE
            CRUMB_RESPONSE=$(curl -u "$JENKINS_USER:$JENKINS_PASSWORD" -s --retry 3 --retry-delay 10 "$JENKINS_URL/crumbIssuer/api/json")
            echo "$CRUMB_RESPONSE"
          }

          # Fetch Jenkins crumb
          CRUMB=$(fetch_crumb | jq -r '.crumb')

          if [ -z "$CRUMB" ]; then
            echo "Failed to fetch Jenkins crumb."
            exit 1
          fi

          # Trigger Jenkins job with crumb
          curl -X POST "$JENKINS_URL/job/$JOB_NAME/build" \
               --user "$JENKINS_USER:$JENKINS_PASSWORD" \
               -H "Jenkins-Crumb:$CRUMB"
