name: Trigger Jenkins on Push

on:
  push:
    branches:
      - muhamed_joulani_final_project

jobs:
  trigger_jenkins_job:
    runs-on: ubuntu-latest

    steps:
      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Trigger Jenkins job
        run: |
          JENKINS_URL="http://100.27.108.130:8080"
          JENKINS_USER="admin"
          JENKINS_PASSWORD="1234"
          JOB_NAME="kub_jen"

          # Fetch Jenkins crumb
          CRUMB=$(curl -u "$JENKINS_USER:$JENKINS_PASSWORD" -s "$JENKINS_URL/crumbIssuer/api/json" | jq -r '.crumbRequestField + ":" + .crumb')

          # Trigger Jenkins job
          curl -X POST "$JENKINS_URL/job/$JOB_NAME/build" \
               --user "$JENKINS_USER:$JENKINS_PASSWORD" \
               -H "$CRUMB"
