name: Trigger Jenkins on Push

on:
  push:
    branches:
      - muhamed_joulani_final_project

jobs:
  trigger_jenkins_job:
    runs-on: ubuntu-latest

    steps:
      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Trigger Jenkins job
        run: |
          JENKINS_URL="http://100.27.108.130:8080"
          JENKINS_USER="mjoulani"
          JENKINS_PASSWORD="1234"
          JOB_NAME="kub_jen"

          # Fetch Jenkins crumb
          CRUMB_RESPONSE=$(curl -u "$JENKINS_USER:$JENKINS_PASSWORD" -s "$JENKINS_URL/crumbIssuer/api/json")
          echo "Crumb response: $CRUMB_RESPONSE"

          if echo "$CRUMB_RESPONSE" | jq . > /dev/null 2>&1; then
            CRUMB=$(echo "$CRUMB_RESPONSE" | jq -r '.crumbRequestField + ":" + .crumb')
            echo "Crumb: $CRUMB"

            # Trigger Jenkins job
            curl -X POST "$JENKINS_URL/job/$JOB_NAME/build" \
                 --user "$JENKINS_USER:$JENKINS_PASSWORD" \
                 -H "$CRUMB"
          else
            echo "Failed to parse crumb response as JSON"
            exit 1
          fi
